### ISSUE TITLE
Compilation error: error CS0618: 'BlorcApplicationBase' is obsolete: 'This class will be removed'

### ISSUE THREAD

**Issue by michael-andreev** [WildGums/Blazorc.PatternFly#234]
## Summary

Hy guys,

first of all thank you for your work, I'm very excited and going to try it in my new project.

I'm getting a complitation error ('BlorcApplicationBase' is obsolete). Seems that it's related with the latest changes in `Blorc.Core` library. I've found a workaround (described below), but probably this project (and QuickStart tutorial) requires some refactoring, because, as far as I can see, some core logic has been changed.

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ ] .NET Standard
 - [x] .NET Core

## Component

`Blorc.PatternFly.Example` project (and any new Blazor project based on QuickStart).

## Version of Library

`Blorc.PatternFly` 1.0.0-alpha0760

## Version of OS(s) listed above with issue

* Windows 10 (latest)
* Fedora 32 (latest)

## Steps to Reproduce

1. `git clone https://github.com/WildGums/Blorc.PatternFly.git`
2. `cd Blorc.PatternFly/src`
3. `dotnet build`

## Expected Behavior

Build succeeded.

## Actual Behavior

Build failed with error:

> .../Blorc.PatternFly/src/Blorc.PatternFly.Example/obj/Debug/net5.0/Razor/App.razor.g.cs(68,32): error CS0618: 'BlorcApplicationBase' is obsolete: 'This class will be removed' [.../Blorc.PatternFly/src/Blorc.PatternFly.Example/Blorc.PatternFly.Example.csproj]

## Found workaround

Add these settings to the `Blorc.PatternFly.Example.csproj` file to supress the error above:

```
  <PropertyGroup>
    <WarningsNotAsErrors>0618</WarningsNotAsErrors>
  </PropertyGroup>
```

**Comment by alexfdezsauco** [comment]
Sorry for the delayed response. The build is fixed.
